apiVersion: apps/v1
kind: Deployment
metadata:
  name: appservice-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: appservice
  template:
    metadata:
      labels:
        app: appservice
    spec:
      containers:
        - name: app-container
          image: boogie1/aiproject:latest
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mariadb://mariadb-service:3306/springai
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: spring-ai-secrets
                  key: db-password
            - name: SPRING_AI_OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: spring-ai-secrets
                  key: openai-api-key
