apiVersion: v1
kind: Secret
metadata:
  name: spring-ai-secrets     # give it a name, e.g. aiproject-secrets
type: Opaque
stringData:
  db-password: <your-db-password>       # your mariadb root password
  openai-api-key: <your-openai-api-key>  # your openai key
