spring.application.name=aiproject
server.port=8082

# datasource - values injected from env variables in pipeline
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mariadb://localhost:3308/spring_ai}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# auto create vector_store table
spring.ai.vectorstore.mariadb.initialize-schema=true

# openai - injected from env variable
spring.ai.openai.api-key=${SPRING_AI_OPENAI_API_KEY}
